#+title: emacs config
#+author: Ángel Castañeda
#+startup: latexpreview

* why not vim?

While I'm very satisfied with [[https://www.lunarvim.org/][lunarvim]] as an IDE and native cli git
for VC, I kinda hate caldav and finding a frontend for my [[https://radicale.org/v3.html][radicale]]
server.

I'm learning emacs for mostly for org-agenda but I'm also exploring
org-roam and magit.

* how I got started

Got a cool base config with org-babel from [[https://youtube.com/playlist?list=PLX2044Ew-UVVv31a0-Qn3dA6Sd_-NyA1n&si=FHsyEvbLXbTQHiyC][uncle dave]] and lots of
really cool show cases from [[https://systemcrafters.net/][system crafters]]. The best channel I've
seen with showcasing emacs features is [[https://www.youtube.com/@protesilaos/][protesilaos]].

* TODOs

** org general [1/7]
- [-] $\LaTeX{}$ previews
  - [X] ez integral stuff
  $$\int_{-\infty}^0 e^x dx = 1$$
  - [ ] actuarial notation package too
  $$a_{\angl{n} i}$$
- [ ] syntax highlighting
- [ ] fancy tables
- [ ] images
- [X] make headers scale by font
- [ ] get sr.ht hook for custom READMEs
- [ ] *most important* don't render anything (tex, images, links) when
  I hover over it

** org-agenda [1/5]
- [X] custom org-agenda view
- [ ] close/unclose dates
- [ ] add colors and such
- [ ] make more TODO DONE etc tags
- [ ] add holidays

** org-roam [2/4]
- [X] learn how to make custom templates for books, authors, etc
- [ ] export to html
- [X] have less ugly graphs generated
- [ ] query tags and transclude results in topic index pages

** frontends to unix stuff

I really wanna avoid having "vendor lockin", so my goal is to
interface with daemons and programs that are portable outside of
emacs.

prime example is maildir/notmuch vs mu4e. I guess I'm breaking my
rules using org mode instead of TeX or markdown, but markup languages
are pure evil anyways.

*** music/mpd [0/1]
- [ ] setup emms

*** email/notmuch+msmtp [1/2]
- [X] notmuch
- [ ] basic email client

*** git/magit [1/5]
- [ ] figure out magit custom signatures at end
- [ ] get used to keybindings
- [X] figure out how to manually edit hunks (just mark then stage)
- [ ] figure out ~git add -f <file>~
- [ ] learn ediff

*** irc/? [0/1]
- [ ] figure out an irc client

*** files/dired [0/1]
- [ ] get good at dired

*** pass/password-store.el [/]
- [ ] interface with pass
